// Pi adapter compile entry point.
//
// compile(coreDir, distDir):
//   1. gray-matter every coreDir/agents/*.md -> AgentSpec.parse
//   2. Rewrite frontmatter to pi shape (name, description, tools, tier);
//      body verbatim; write distDir/agents/<name>.md.
//   3. Generate the mode extension's orchestrator-contract module
//      from coreDir/agents/orchestrator.md plus the rendered chains
//      from coreDir/workflow.yaml. Single source of truth for the
//      d3r system prompt.
//   4. Force-symlink extensions/subagent and extensions/mode
//      into distDir/extensions/.
//   5. Force-symlink coreDir/templates -> distDir/templates.
//   6. Return BuildReport. Throw on any zod failure.

import {
	mkdir,
	readFile,
	readdir,
	rm,
	stat,
	symlink,
	writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import matter from "gray-matter";
import { parse as parseYaml } from "yaml";
import type { ChainStep } from "../../core/schema.ts";
// oxlint-disable-next-line no-duplicate-imports
import { AgentSpec, Workflow } from "../../core/schema.ts";
import { registry } from "@d3r/tools";
import { piToolMap } from "./capability-map.ts";

const KNOWN_TOOL_NAMES = new Set(registry.map((t) => t.name));

export interface BuildReport {
	agents: number;
	extensions: string[];
}

const HERE = path.dirname(fileURLToPath(import.meta.url));
const EXTENSIONS_SRC = path.join(HERE, "extensions");
const WANTED_EXTENSIONS = ["d3r-tools", "subagent", "mode"] as const;
const ORCHESTRATOR_AGENT_FILE = "orchestrator.md";
const ORCHESTRATOR_CONTRACT_OUT = path.join(
	EXTENSIONS_SRC,
	"mode",
	"orchestrator-contract.generated.ts",
);

const forceSymlink = async (
	target: string,
	linkPath: string,
): Promise<void> => {
	await rm(linkPath, { force: true, recursive: true });
	await mkdir(path.dirname(linkPath), { recursive: true });
	await symlink(target, linkPath);
};

const renderStep = (step: ChainStep, depth = 0): string => {
	const indent = "  ".repeat(depth);
	switch (step.kind) {
		case "agent": {
			return `${indent}- agent: ${step.name}`;
		}
		case "parallel": {
			return `${indent}- parallel: ${step.agents.join(", ")}`;
		}
		case "human": {
			return `${indent}- human: ${step.prompt}`;
		}
		case "loop": {
			const header = `${indent}- loop (max ${step.max}):`;
			const body = step.body.map((s) => renderStep(s, depth + 1)).join("\n");
			return `${header}\n${body}`;
		}
	}
};

const renderChains = (wf: Workflow): string => {
	const sections = Object.entries(wf.commands).map(([name, cmd]) => {
		const steps = cmd.chain.map((s) => renderStep(s)).join("\n");
		const reviews =
			cmd.reviews_default !== undefined
				? `\n\n_reviews_default: ${cmd.reviews_default}_`
				: "";
		return `### ${name}\n\n${cmd.description}\n\n${steps}${reviews}`;
	});
	return ["## Chains", "", ...sections].join("\n\n");
};

// Read orchestrator.md, strip frontmatter, append the rendered chain
// definitions from workflow.yaml, and emit a TS module the mode
// extension can import. Generated file is gitignored; it lives inside
// the extension dir because the extension is symlinked into dist (and
// from there into the user's pi config), so a sibling file is the
// only path-stable way to ship the contract body.
const compileOrchestratorContract = async (coreDir: string): Promise<void> => {
	const src = path.join(coreDir, "agents", ORCHESTRATOR_AGENT_FILE);
	const raw = await readFile(src, "utf8");
	const body = matter(raw).content.trim();
	const wfRaw = await readFile(path.join(coreDir, "workflow.yaml"), "utf8");
	const wf = Workflow.parse(parseYaml(wfRaw));
	const chains = renderChains(wf);
	const combined = `${body}\n\n${chains}\n`;
	const literal = JSON.stringify(combined);
	const out = `// AUTO-GENERATED by adapters/pi/compile.ts from
// core/agents/${ORCHESTRATOR_AGENT_FILE} + core/workflow.yaml. Do not
// edit by hand.

export const ORCHESTRATOR_CONTRACT = ${literal};
`;
	await writeFile(ORCHESTRATOR_CONTRACT_OUT, out, "utf8");
};

const compileOneAgent = async (
	srcPath: string,
	outPath: string,
): Promise<void> => {
	const raw = await readFile(srcPath, "utf8");
	const parsed = matter(raw);
	const spec = AgentSpec.parse(parsed.data);
	for (const t of spec.tools) {
		if (!KNOWN_TOOL_NAMES.has(t)) {
			const known = [...KNOWN_TOOL_NAMES].toSorted().join(", ");
			throw new Error(
				`agent "${spec.name}" lists unknown tool "${t}"; known: ${known}`,
			);
		}
	}
	const tools = [
		...new Set([
			...spec.capabilities.flatMap((c) => piToolMap[c]),
			...spec.tools,
		]),
	];
	const piFrontmatter = {
		name: spec.name,
		description: spec.description,
		tools: tools.join(", "),
		tier: spec.tier,
	};
	const out = matter.stringify(parsed.content, piFrontmatter);
	await writeFile(outPath, out, "utf8");
};

const compileAgents = async (
	coreDir: string,
	distDir: string,
): Promise<number> => {
	const agentsSrc = path.join(coreDir, "agents");
	const agentsOut = path.join(distDir, "agents");
	await mkdir(agentsOut, { recursive: true });
	const entries = await readdir(agentsSrc);
	const files = entries.filter((f) => f.endsWith(".md"));
	await Promise.all(
		files.map((f) =>
			compileOneAgent(path.join(agentsSrc, f), path.join(agentsOut, f)),
		),
	);
	return files.length;
};

const linkOneExtension = async (
	name: string,
	distDir: string,
): Promise<string> => {
	const src = path.join(EXTENSIONS_SRC, name);
	const dest = path.join(distDir, "extensions", name);
	await stat(src);
	await forceSymlink(src, dest);
	return name;
};

const linkExtensions = async (distDir: string): Promise<string[]> =>
	Promise.all(WANTED_EXTENSIONS.map((name) => linkOneExtension(name, distDir)));

const linkTemplates = async (
	coreDir: string,
	distDir: string,
): Promise<void> => {
	const src = path.join(coreDir, "templates");
	const dest = path.join(distDir, "templates");
	await forceSymlink(src, dest);
};

export const compile = async (
	coreDir: string,
	distDir: string = path.join(HERE, "dist"),
): Promise<BuildReport> => {
	await mkdir(distDir, { recursive: true });
	await compileOrchestratorContract(coreDir);
	const agents = await compileAgents(coreDir, distDir);
	const extensions = await linkExtensions(distDir);
	await linkTemplates(coreDir, distDir);
	const report: BuildReport = { agents, extensions };
	console.log(
		`[compile:pi] agents=${agents} extensions=[${extensions.join(", ")}]`,
	);
	return report;
};

// CLI entry: invoked via `pnpm --filter @d3r/adapter-pi build`.
// Resolves the workspace's @d3r/core root relative to this file and
// runs the compile against the package's own dist/.
if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
	const coreDir = path.resolve(HERE, "../../core");
	await compile(coreDir);
}
