// Pi adapter compile entry point.
//
// compile(coreDir, distDir):
//   1. gray-matter every coreDir/agents/*.md -> AgentSpec.parse
//   2. Rewrite frontmatter to pi shape (name, description, tools, tier);
//      body verbatim; write distDir/agents/<name>.md.
//   3. Generate the mode extension's orchestrator-contract module
//      from coreDir/agents/orchestrator.md plus the rendered chains
//      from coreDir/workflow.yaml. Single source of truth for the
//      d3r system prompt.
//   4. Return BuildReport. Throw on any zod failure.

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { parse as parseYaml } from "yaml";
import type { ChainStep } from "@d3r/core";
// oxlint-disable-next-line no-duplicate-imports
import { AgentSpec, Workflow } from "@d3r/core";
import { piToolMap } from "./capability-map.ts";

export interface BuildReport {
	agents: number;
}

const HERE = path.dirname(fileURLToPath(import.meta.url));
const EXTENSIONS_SRC = path.join(HERE, "extensions");
const ORCHESTRATOR_AGENT_FILE = "orchestrator.md";
const ORCHESTRATOR_CONTRACT_OUT = path.join(
	EXTENSIONS_SRC,
	"mode",
	"orchestrator-contract.generated.ts",
);

const renderStep = (step: ChainStep, depth = 0): string => {
	const indent = "  ".repeat(depth);
	switch (step.kind) {
		case "agent": {
			return `${indent}- agent: ${step.name}`;
		}
		case "parallel": {
			return `${indent}- parallel: ${step.agents.join(", ")}`;
		}
		case "human": {
			return `${indent}- human: ${step.prompt}`;
		}
		case "loop": {
			const header = `${indent}- loop (max ${step.max}):`;
			const body = step.body.map((s) => renderStep(s, depth + 1)).join("\n");
			return `${header}\n${body}`;
		}
	}
};

const renderChains = (wf: Workflow): string => {
	const sections = Object.entries(wf.commands).map(([name, cmd]) => {
		const steps = cmd.chain.map((s) => renderStep(s)).join("\n");
		const reviews =
			cmd.reviews_default !== undefined
				? `\n\n_reviews_default: ${cmd.reviews_default}_`
				: "";
		return `### ${name}\n\n${cmd.description}\n\n${steps}${reviews}`;
	});
	return ["## Chains", "", ...sections].join("\n\n");
};

// Read orchestrator.md, strip frontmatter, append the rendered chain
// definitions from workflow.yaml, and emit a TS module the mode
// extension can import. Generated file is gitignored; it lives inside
// the extension dir because mode/index.ts imports it as a sibling
// source file when pi loads the extension.
const compileOrchestratorContract = async (coreDir: string): Promise<void> => {
	const src = path.join(coreDir, "agents", ORCHESTRATOR_AGENT_FILE);
	const raw = await readFile(src, "utf8");
	const body = matter(raw).content.trim();
	const wfRaw = await readFile(path.join(coreDir, "workflow.yaml"), "utf8");
	const wf = Workflow.parse(parseYaml(wfRaw));
	const chains = renderChains(wf);
	const combined = `${body}\n\n${chains}\n`;
	const literal = JSON.stringify(combined);
	const out = `// AUTO-GENERATED by adapters/pi/compile.ts from
// core/agents/${ORCHESTRATOR_AGENT_FILE} + core/workflow.yaml. Do not
// edit by hand.

export const ORCHESTRATOR_CONTRACT = ${literal};
`;
	await writeFile(ORCHESTRATOR_CONTRACT_OUT, out, "utf8");
};

const compileOneAgent = async (
	srcPath: string,
	outPath: string,
): Promise<void> => {
	const raw = await readFile(srcPath, "utf8");
	const parsed = matter(raw);
	const spec = AgentSpec.parse(parsed.data);
	const tools = [...new Set(spec.capabilities.flatMap((c) => piToolMap[c]))];
	const piFrontmatter = {
		name: spec.name,
		description: spec.description,
		tools: tools.join(", "),
		tier: spec.tier,
	};
	const out = matter.stringify(parsed.content, piFrontmatter);
	await writeFile(outPath, out, "utf8");
};

const compileAgents = async (
	coreDir: string,
	distDir: string,
): Promise<number> => {
	const agentsSrc = path.join(coreDir, "agents");
	const agentsOut = path.join(distDir, "agents");
	await mkdir(agentsOut, { recursive: true });
	const entries = await readdir(agentsSrc);
	const files = entries.filter((f) => f.endsWith(".md"));
	await Promise.all(
		files.map((f) =>
			compileOneAgent(path.join(agentsSrc, f), path.join(agentsOut, f)),
		),
	);
	return files.length;
};

export const compile = async (
	coreDir: string,
	distDir: string,
): Promise<BuildReport> => {
	await mkdir(distDir, { recursive: true });
	await compileOrchestratorContract(coreDir);
	const agents = await compileAgents(coreDir, distDir);
	const report: BuildReport = { agents };
	console.log(`[compile:pi] agents=${agents}`);
	return report;
};
